spring:
  cloud:
    stream:
      bindings:
        purchaseProducer-out-0:
          destination: purchase-topic
        productProducer-out-0:
          destination: product-topic
      kafka:
        binder:
          brokers: localhost:29092
  data:
    mongodb:
      host: localhost
      port: 27070
      database: orderDB
      username: admin
      password: admin
      authentication-database: admin