version: '3.7'

services:
  mongodb:
    image: mongo:6.0.13
    container_name: "mongodb"
    ports:
      - 27070:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - type: bind
        source: ./data
        target: /data/db